### ISSUE TITLE
Infinite recursion when iterating

### ISSUE THREAD

**Issue by danog** [amphp/mysql#133]
This code causes infinite recursion:

```
<?php declare(strict_types=1);

require 'vendor/autoload.php';

$config = Amp\Mysql\MysqlConfig::fromString(
    "host=127.0.0.1 user=daniil db=test"
);

$pool = new Amp\Mysql\MysqlConnectionPool($config);

foreach ($pool->execute("SELECT * FROM 6565201688_MTProto_chats") as $result) {
    var_dump($result);
}
```

**Comment by danog** [comment]
Using the table at https://paste.daniil.it/dump.sql

**Comment by danog** [comment]
With mariadb from 11.2.2-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

**Comment by danog** [comment]
The culprit seems to be https://github.com/amphp/sql-common/commit/de27f1c3756218c76ff292f1710be1da4a573d71

**Comment by trowski** [comment]
The issue seems to be `yield from` [here](https://github.com/amphp/sql-common/commit/de27f1c3756218c76ff292f1710be1da4a573d71#diff-f846eee8e2403be7ecd2ce5a6d4b0238aea629092633cb68bea10f7bff77ca21R49). Swapping that to `foreach ($result as $row) yield $row` fixes the segfault. Seems we found a PHP bug, though I'm not sure how to repo it in isolation.

**Comment by Bilge** [comment]
OK, but we really need to reproduce it 😞
